### PR TITLE
Setup test environment

### PR DESCRIPTION
**Pull request by heliocorreia**
Fix: #1

### CODE REVIEW

**Comment by heliocorreia** [comment]
@dmvieira I can handle the python 2.7, but I think that the coverage threshold may have its own issue, once the testing environment is all set. Do you agree?

**Comment by dmvieira** [comment]
Alright! I did another issue here: https://github.com/globocom/gsenha-python/issues/6

**Comment by dmvieira** [comment]
It's still broken because more-itertools is not available for Python 2.7

**Comment by heliocorreia** [comment]
@dmvieira, I believe this is a dependency issue, not a testing setup issue.

The more-itertools 5.0.0 is the last Python 2.7 compatible version, and the Python 2.7 will reach the end of its life on January 1st, 2020. Do you really need to support Python 2.7? If so, we better have another issue for that. Do you agree?

**Comment by dmvieira** [comment]
Ok, I did another one issue: https://github.com/globocom/gsenha-python/issues/7

**Pull request merged**
